version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      octokit:
        patterns:
          - '@octokit/*'
          - '@actions/*'
      tooling:
        patterns:
          - vitest
          - '@vitest/*'
          - '@vercel/ncc'
          - typescript
          - '@biomejs/*'
